export const galleryData = [
  {
    id: 1,
    badgeTitle: "Clothes",
    badgeBKColor: "#D6293E",
    description: "Nice clothes help you look good in society.",
    background: "./assets/images/category/Clothes.jpg",
    alt: "clothes",
    to: "/#",
  },
  {
    id: 2,
    badgeTitle: "Super Market",
    badgeBKColor: "#297FD6",
    description: "You don't need to go to crowded stores for shopping.",
    background: "./assets/images/category/SuperMarket.jpg",
    alt: "superMarket",
    to: "/#",
  },
  {
    id: 3,
    badgeTitle: "Cell Phones",
    badgeBKColor: "#000000",
    description: "Buy original mobile phones at amazing prices.",
    background: "./assets/images/category/CellPhones.jpg",
    alt: "Cellphones",
    to: "/#",
  },
  {
    id: 4,
    badgeTitle: "Books & Podcasts",
    badgeBKColor: "#12B364",
    description: "Today, books and podcasts have a special value for us.",
    background: "./assets/images/category/Books&Podcasts.jpg",
    alt: "book",
    to: "/#",
  },
  {
    id: 5,
    badgeTitle: "Shoes",
    badgeBKColor: "#2937D6",
    description:
      "Leather and formal shoes, new sports pants for beauty lovers.",
    background: "./assets/images/category/Shoes.jpg",
    alt: "Shoes",
    to: "/#",
  },
  {
    id: 6,
    badgeTitle: "Health & Personal Care",
    badgeBKColor: "#D629C5",
    description:
      "Beauty and cosmetic products, all kinds of perfumes and attractive accessories.",
    background: "./assets/images/category/Health&PersonalCare.jpg",
    alt: "Health & Personal Care",
    to: "/#",
  },
  {
    id: 7,
    badgeTitle: "Sports Goods",
    badgeBKColor: "#FF8400",
    description:
      "You must have the right equipment to exercise. Find them here.",
    background: "./assets/images/category/SportsGoods.jpg",
    alt: "Sports Goods",
    to: "/#",
  },
  {
    id: 8,
    badgeTitle: "Stationery",
    badgeBKColor: "#2CB322",
    description:
      "Paper, pencils and pens, supplies and stationery for your beloved children.",
    background: "./assets/images/category/Stationery.jpg",
    alt: "Stationery",
    to: "/#",
  },
];
export const servicesData = [
  {
    id: 1,
    logo: "./assets/svg/Dolbi-Elite.svg",
    title: "Dolbi Elite",
    description: "Multi-tasking, gaming or binge watching your favorite.",
    alt: "clothes",
    to: "/#",
  },
  {
    id: 2,
    logo: "./assets/svg/Dolbi-Pro.svg",
    title: "Dolbi Pro",
    description: "Follow your after-sales service and special offers.",
    alt: "clothes",
    to: "/#",
  },
  {
    id: 3,
    logo: "./assets/svg/Dolbi-Club.svg",
    title: "Dolbi Club",
    description:
      "Free shipping, product insurance and choice of shipping method.",
    alt: "clothes",
    to: "/#",
  },
  {
    id: 4,
    logo: "./assets/svg/Dolbi-Time.svg",
    title: "Dolbi Time",
    description: "Return or sell the product you bought without any hassle.",
    alt: "clothes",
    to: "/#",
  },
];
